

Vagrant.configure("2") do |config|
    (1..1).each do |i|
      config.vm.define "node#{i}" do |node|
        node.vm.box = "ubuntu/trusty64"
          node.vm.provider "virtualbox" do |v|
            v.name = "hadoop-node-#{i}"
            v.memory = 8192
          end
          node.vm.network "public_network", ip: "192.168.0.#{i+1}"
          node.vm.hostname = "hadoop-node-#{i}"
          node.vm.network "forwarded_port", guest: 7180, host: 7180
      end
    end
    (2..8).each do |i|
    	config.vm.define "node#{i}" do |node|
    		node.vm.box = "ubuntu/trusty64"
      		node.vm.provider "virtualbox" do |v|
      			v.name = "hadoop-node-#{i}"
      			v.memory = 2048
      		end
          node.vm.network "public_network", ip: "192.168.0.#{i+1}"
      		node.vm.hostname = "hadoop-node-#{i}"
    	end
    end
end
