

Vagrant.configure("2") do |config|

    (1..16).each do |i|
    	config.vm.define "node#{i}" do |node|
    		node.vm.box = "bento/ubuntu-14.04"
      		node.vm.provider "virtualbox" do |v|
      			v.name = "hadoop-node-#{i}"
      			v.memory = 1024
      		end
      		node.vm.network "public_network", ip: "192.168.0.#{i+24}", bridge: "wlp11s0"
      		node.vm.hostname = "hadoopNode#{i}"
    	end
    end
end
