#nodes_config = (JSON.parse(File.read("nodes.json")))['nodes']


Vagrant.configure("2") do |config|
    config.vm.define :master do |master|
      master.vm.box = "bento/centos-6.7"
      master.vm.provider :virtualbox do |v|
      v.name = "vm-cluster-node1"
      v.customize ["modifyvm", :id, "--memory", "2048"]
      end
      master.vm.network :public_network
      master.vm.hostname = "vm-cluster-node1"
      #master.vm.provision :shell, :inline => $master_script
    end

    config.vm.define :slave1 do |slave1|
      slave1.vm.box = "bento/centos-6.7"
      slave1.vm.provider :virtualbox do |v|
      v.name = "vm-cluster-node2"
      v.customize ["modifyvm", :id, "--memory", "2048"]
      end
      slave1.vm.network :public_network
      slave1.vm.hostname = "vm-cluster-node2"
      #slave1.vm.provision :shell, :inline => $slave1_script
    end

    config.vm.define :slave2 do |slave2|
      slave2.vm.box = "bento/centos-6.7"
      slave2.vm.provider :virtualbox do |v|
      v.name = "vm-cluster-node3"
      v.customize ["modifyvm", :id, "--memory", "2048"]
      end
      slave2.vm.network :public_network
      slave2.vm.hostname = "vm-cluster-node3"
      #slave2.vm.provision :shell, :inline => $slave2_script
    end

end
