./mininet/util/m h1 python sendPacket.py
./mininet/util/m h2 python sendPacket.py
./mininet/util/m h3 python sendPacket.py
./mininet/util/m h4 python sendPacket.py
./mininet/util/m h5 python sendPacket.py
./mininet/util/m h6 python sendPacket.py
./mininet/util/m h7 python sendPacket.py
./mininet/util/m h8 python sendPacket.py
./mininet/util/m h9 python sendPacket.py
./mininet/util/m h10 python sendPacket.py
./mininet/util/m h11 python sendPacket.py
./mininet/util/m h12 python sendPacket.py
./mininet/util/m h13 python sendPacket.py
./mininet/util/m h14 python sendPacket.py
./mininet/util/m h15 python sendPacket.py
./mininet/util/m h16 python sendPacket.py